AccountManagerPlugin: Restore 0.11 compatibility, refs #8963.
Trac 0.11 produces duplicated HTTP request arguments when sending POST request
of account details admin page received with GET arguments before.
Now explicitly setting an action URL for POST results in consistent behavior.

And another occurance of tag_ is replaced here, to get rid of !TypeError
(unexpected keyword argument 'user') again.